# Generated by Django 2.2.7 on 2019-12-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_student_school'),
        ('tiaozhancup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaozhancup',
            name='is_review_by_boss',
            field=models.BooleanField(default=False, null=True, verbose_name='专家审核'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='is_review_by_college',
            field=models.BooleanField(default=False, null=True, verbose_name='校审核'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='is_review_by_school',
            field=models.BooleanField(default=False, null=True, verbose_name='院审核'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='student',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tiaozhancup', to='dashboard.Student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
