# Generated by Django 2.2.7 on 2019-12-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0003_auto_20191216_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_pool', models.CharField(max_length=700, null=True, verbose_name='专家池')),
            ],
        ),
        migrations.CreateModel(
            name='College_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_pool', models.CharField(max_length=700, null=True, verbose_name='校池')),
            ],
        ),
        migrations.CreateModel(
            name='School_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('econ', models.CharField(max_length=500, null=True, verbose_name='经济管理学院')),
                ('cs', models.CharField(max_length=500, null=True, verbose_name='智能制造学部')),
                ('law', models.CharField(max_length=500, null=True, verbose_name='政法学院')),
                ('lietra', models.CharField(max_length=500, null=True, verbose_name='文学院')),
                ('fore', models.CharField(max_length=500, null=True, verbose_name='外国语学院')),
                ('math', models.CharField(max_length=500, null=True, verbose_name='数学与计算科学学院')),
                ('phys', models.CharField(max_length=500, null=True, verbose_name='应用物理与材料学院')),
                ('civil', models.CharField(max_length=500, null=True, verbose_name='土木建筑学院')),
                ('bio', models.CharField(max_length=500, null=True, verbose_name='生物科技与大健康学院')),
                ('weave', models.CharField(max_length=500, null=True, verbose_name='纺织材料与工程学院')),
                ('art', models.CharField(max_length=500, null=True, verbose_name='艺术学院')),
            ],
        ),
    ]
