# Generated by Django 2.2.7 on 2019-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0004_boss_pool_college_pool_school_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaozhancup',
            name='boss_staff_give',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='college_staff_give',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='scool_staff_give',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
