# Generated by Django 2.2.7 on 2019-12-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0005_auto_20191222_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiaozhancup',
            name='boss_staff_give',
            field=models.CharField(default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='college_staff_give',
            field=models.CharField(default='[]', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='scool_staff_give',
            field=models.CharField(default='[]', max_length=500, null=True),
        ),
    ]
