# Generated by Django 2.2.7 on 2019-12-23 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0008_auto_20191223_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boss_pool',
            old_name='college_pool',
            new_name='boss_pool',
        ),
    ]
