# Generated by Django 2.2.7 on 2019-12-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0009_auto_20191223_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiaozhancup',
            name='test',
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='address_usually',
            field=models.CharField(max_length=100, null=True, verbose_name='常住通讯地址'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='address_whole',
            field=models.CharField(max_length=100, null=True, verbose_name='通讯地址'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='applyer',
            field=models.CharField(max_length=50, null=True, verbose_name='申报人姓名'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='birth',
            field=models.CharField(max_length=50, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='class_four',
            field=models.CharField(max_length=50, null=True, verbose_name='四级分类'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='class_one',
            field=models.CharField(max_length=50, null=True, verbose_name='小类'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='class_three',
            field=models.CharField(max_length=50, null=True, verbose_name='三级分类'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='detail_intro',
            field=models.CharField(max_length=500, null=True, verbose_name='详细介绍'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='dorm_phone',
            field=models.CharField(max_length=50, null=True, verbose_name='学校宿舍电话'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='entry_year',
            field=models.CharField(max_length=50, null=True, verbose_name='入学年份'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='gender',
            field=models.CharField(max_length=50, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='grade',
            field=models.CharField(max_length=50, null=True, verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='gradua_paper_title',
            field=models.CharField(max_length=100, null=True, verbose_name='毕业论文题目'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='home_number',
            field=models.CharField(max_length=50, null=True, verbose_name='家庭电话'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='id_number',
            field=models.CharField(max_length=50, null=True, verbose_name='证件号码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='id_type',
            field=models.CharField(max_length=50, null=True, verbose_name='证件类型'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='major',
            field=models.CharField(max_length=50, null=True, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='mobile_number',
            field=models.CharField(max_length=50, null=True, verbose_name='移动电话'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='overall_type',
            field=models.CharField(max_length=50, null=True, verbose_name='申报种类'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='postal_code',
            field=models.CharField(max_length=50, null=True, verbose_name='邮政编码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='postscript',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_logic',
            field=models.CharField(max_length=500, null=True, verbose_name='作品设计、发明的目的和基本思路、创新点、技术关键和主要技术目标：'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_name',
            field=models.CharField(max_length=50, null=True, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_past',
            field=models.CharField(max_length=100, null=True, verbose_name='作品在何时何地何种机构举行的评审、鉴定、评比、展示等活动中获奖及鉴定结果'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_patent',
            field=models.CharField(max_length=300, null=True, verbose_name='专利申报情况'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_predict',
            field=models.CharField(max_length=500, null=True, verbose_name='使用说明及该作品的技术特点和优势，提供该作品的适用范围及推广前景的技术性说明及市场分析和经济效益预测'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_problem_statement',
            field=models.CharField(max_length=500, null=True, verbose_name='当前国内外同类型课题研究水平概述'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_show_way',
            field=models.CharField(max_length=100, null=True, verbose_name='作品可展示形式'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='project_stage',
            field=models.CharField(max_length=100, null=True, verbose_name='作品所处阶段'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_address',
            field=models.CharField(max_length=100, null=True, verbose_name='推荐人通讯地址'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_age',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人年龄'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_comment',
            field=models.CharField(max_length=100, null=True, verbose_name='推荐人请对作品的意义、技术水平、适用范围及推广前景作出评价'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_fact_check',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人请对申报者申报情况的真实性作出阐述'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_gender',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人姓别'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_home_number',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人住宅号码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_mobile_number',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人电话号码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_name',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人姓名'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_office',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人工作单位'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_other_comment',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人其他说明'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_postal_code',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人邮政编码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='recommend_title',
            field=models.CharField(max_length=50, null=True, verbose_name='推荐人职称'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='school',
            field=models.CharField(max_length=50, null=True, verbose_name='高校'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='school_id',
            field=models.CharField(max_length=50, null=True, verbose_name='学号'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='school_type',
            field=models.CharField(max_length=50, null=True, verbose_name='学制'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='technique_point',
            field=models.CharField(max_length=500, null=True, verbose_name='作品的科学性、先进性'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='technique_transport_method',
            field=models.CharField(max_length=100, null=True, verbose_name='技术转让方式'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='top_academic_level',
            field=models.CharField(max_length=50, null=True, verbose_name='最高学历'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='upload_affix',
            field=models.CharField(max_length=100, null=True, verbose_name='上传附件材料'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='upload_paper',
            field=models.CharField(max_length=100, null=True, verbose_name='上传论文文档'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='upload_picture',
            field=models.CharField(max_length=100, null=True, verbose_name='上传图片'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='upload_video',
            field=models.CharField(max_length=100, null=True, verbose_name='上传视频'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='wechat_number',
            field=models.CharField(max_length=50, null=True, verbose_name='微信号'),
        ),
    ]
