# Generated by Django 2.2.7 on 2019-12-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0010_auto_20191225_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaozhancup',
            name='postal_code_user',
            field=models.CharField(max_length=50, null=True, verbose_name='常住邮政编码'),
        ),
        migrations.AddField(
            model_name='tiaozhancup',
            name='short_intro',
            field=models.CharField(max_length=1000, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='detail_intro',
            field=models.CharField(max_length=4000, null=True, verbose_name='详细介绍'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='postscript',
            field=models.CharField(max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_past',
            field=models.CharField(max_length=1000, null=True, verbose_name='作品在何时何地何种机构举行的评审、鉴定、评比、展示等活动中获奖及鉴定结果'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_patent',
            field=models.CharField(max_length=500, null=True, verbose_name='专利申报情况'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_predict',
            field=models.CharField(max_length=2000, null=True, verbose_name='使用说明及该作品的技术特点和优势，提供该作品的适用范围及推广前景的技术性说明及市场分析和经济效益预测'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_problem_statement',
            field=models.CharField(max_length=2000, null=True, verbose_name='当前国内外同类型课题研究水平概述'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_show_way',
            field=models.CharField(max_length=300, null=True, verbose_name='作品可展示形式'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='project_stage',
            field=models.CharField(max_length=300, null=True, verbose_name='作品所处阶段'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_comment',
            field=models.CharField(max_length=2000, null=True, verbose_name='推荐人请对作品的意义、技术水平、适用范围及推广前景作出评价'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_fact_check',
            field=models.CharField(max_length=1000, null=True, verbose_name='推荐人请对申报者申报情况的真实性作出阐述'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_other_comment',
            field=models.CharField(max_length=1000, null=True, verbose_name='推荐人其他说明'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='technique_point',
            field=models.CharField(max_length=1000, null=True, verbose_name='作品的科学性、先进性'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='technique_transport_method',
            field=models.CharField(max_length=300, null=True, verbose_name='技术转让方式'),
        ),
    ]
