# Generated by Django 2.2.7 on 2019-12-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0011_auto_20191226_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiaozhancup',
            name='class_four',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='四级分类'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='class_three',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='三级分类'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='postscript',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_home_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推荐人住宅号码'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_other_comment',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='推荐人其他说明'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='recommend_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='推荐人职称'),
        ),
    ]
