# Generated by Django 2.2.7 on 2019-12-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0012_auto_20191226_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaozhancup',
            name='request_type',
            field=models.CharField(max_length=50, null=True, verbose_name='申报种类'),
        ),
        migrations.AlterField(
            model_name='tiaozhancup',
            name='overall_type',
            field=models.CharField(max_length=50, null=True, verbose_name='大类'),
        ),
    ]
