# Generated by Django 2.2.7 on 2020-01-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0013_auto_20191226_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiaozhancup',
            name='upload_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提交时间:'),
        ),
    ]
