# Generated by Django 2.2.7 on 2020-01-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiaozhancup', '0014_tiaozhancup_upload_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_pool', models.CharField(default='[]', max_length=700, verbose_name='专家池')),
            ],
        ),
    ]
