# Generated by Django 2.2.7 on 2019-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='SID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
