# Generated by Django 2.2.7 on 2019-11-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191115_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='really_a_teacher',
            field=models.BooleanField(default=False, verbose_name='真的是老师吗 ?'),
        ),
    ]
