# Generated by Django 2.2.7 on 2019-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191116_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
