# Generated by Django 2.2.7 on 2019-11-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20191119_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='authorization_for_contest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
