# Generated by Django 2.2.7 on 2020-01-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200104_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='SID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='TID',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
