# Generated by Django 2.2.7 on 2020-01-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200104_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='TID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
