# Generated by Django 2.2.7 on 2019-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191113_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(default=999, max_length=50, unique=True),
        ),
    ]
