# Generated by Django 2.2.7 on 2019-11-22 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0009_auto_20191120_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_department', models.CharField(max_length=100)),
                ('apply_time', models.CharField(max_length=100)),
                ('applyer', models.CharField(max_length=100)),
                ('contact_info', models.CharField(max_length=100)),
                ('apply_place', models.CharField(max_length=100)),
                ('what_u_need_to_do', models.CharField(max_length=500)),
                ('equipment_u_want', models.CharField(max_length=100)),
                ('guiding_unit_opnion', models.CharField(max_length=100)),
                ('discipline_unit_opnion', models.CharField(max_length=100)),
                ('ccyl_opnion', models.CharField(max_length=100)),
                ('have_registered', models.BooleanField(default=False, null=True, verbose_name='have_registered')),
                ('is_pass', models.BooleanField(default=False, null=True, verbose_name='is_pass')),
                ('is_fail', models.BooleanField(default=False, null=True, verbose_name='is_fail')),
                ('is_reviewing', models.BooleanField(default=True, null=True, verbose_name='is_reviewing')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content1', to='dashboard.Student')),
            ],
        ),
    ]
