# Generated by Django 2.2.7 on 2019-11-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest1',
            name='apply_department',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='apply_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='apply_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='applyer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='ccyl_opnion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='contact_info',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='discipline_unit_opnion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='equipment_u_want',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='guiding_unit_opnion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='what_u_need_to_do',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
