# Generated by Django 2.2.7 on 2019-11-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest1', '0004_auto_20191123_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest1',
            name='ccyl_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='团委留言:'),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='ccyl_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='团委决定'),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='discipline_unit_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='校律委留言:'),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='discipline_unit_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='校律委决定'),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='guiding_unit_comment',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='厅室管理员留言:'),
        ),
        migrations.AlterField(
            model_name='contest1',
            name='guiding_unit_decision',
            field=models.BooleanField(blank=True, null=True, verbose_name='厅室管理员决定'),
        ),
    ]
