# Generated by Django 2.2.7 on 2020-01-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest1', '0005_auto_20191126_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest1',
            name='apply_place_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contest1',
            name='upload_time',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='提交时间:'),
        ),
    ]
