# Generated by Django 2.2.7 on 2020-01-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest1', '0006_auto_20200106_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest1',
            name='is_review_by_stage2',
            field=models.BooleanField(default=False, null=True, verbose_name='校律委人员正在审核'),
        ),
        migrations.AddField(
            model_name='contest1',
            name='is_review_by_stage3',
            field=models.BooleanField(default=False, null=True, verbose_name='团委人员正在审核'),
        ),
    ]
